# Generated by Django 5.2.4 on 2026-06-19 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('source_channel', models.CharField(db_index=True, max_length=50)),
                ('card_type', models.CharField(choices=[('credit', '신용카드'), ('debit', '체크카드')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=1000)),
                ('annual_fee', models.PositiveIntegerField(default=0)),
                ('previous_month_requirement', models.PositiveIntegerField(default=0)),
                ('monthly_discount_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('raw', '원본'), ('normalized', '정규화'), ('validated', '검증 완료'), ('active', '추천 사용'), ('review_required', '검토 필요'), ('invalid', '유효하지 않음'), ('inactive', '비활성')], db_index=True, default='raw', max_length=20)),
                ('raw_text', models.TextField()),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['issuer', 'name'],
                'constraints': [models.UniqueConstraint(fields=('source_channel', 'external_id'), name='unique_card_external_id_per_source')],
            },
        ),
        migrations.CreateModel(
            name='BenefitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('rate', '비율'), ('amount', '정액')], max_length=10)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_transaction_amount', models.PositiveIntegerField(default=0)),
                ('per_transaction_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_monthly_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('category_monthly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('merchant_scope', models.JSONField(blank=True, default=list)),
                ('channel', models.CharField(default='all', max_length=10)),
                ('condition_text', models.TextField(blank=True)),
                ('exclusion_text', models.TextField(blank=True)),
                ('raw_text', models.TextField()),
                ('parse_status', models.CharField(choices=[('raw', '원본'), ('normalized', '정규화'), ('validated', '검증 완료'), ('active', '추천 사용'), ('review_required', '검토 필요'), ('invalid', '유효하지 않음'), ('inactive', '비활성')], db_index=True, default='raw', max_length=20)),
                ('unsupported_conditions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='finance.cardproduct')),
            ],
            options={
                'ordering': ['card_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('raw_html', models.TextField()),
                ('content_checksum', models.CharField(max_length=80)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='finance.cardproduct')),
                ('crawl_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='finance.crawlitem')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('local_path', models.CharField(blank=True, max_length=1000)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=80)),
                ('download_status', models.CharField(choices=[('pending', '대기'), ('fetching', '수집 중'), ('success', '성공'), ('retry_pending', '재시도 대기'), ('paused', '일시 중단'), ('failed', '실패')], default='pending', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='finance.cardproduct')),
            ],
            options={
                'ordering': ['card_id', '-is_primary', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('card', 'source_url'), name='unique_card_image_source')],
            },
        ),
    ]
