# Generated by Django 5.2.4 on 2026-06-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cardproduct_benefitrule_crawlsnapshot_cardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='annual_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CardBenefitTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='card_total', max_length=100)),
                ('minimum_spending', models.PositiveIntegerField()),
                ('maximum_spending', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_discount_limit', models.PositiveIntegerField()),
                ('raw_text', models.TextField()),
                ('parse_status', models.CharField(choices=[('raw', '원본'), ('normalized', '정규화'), ('validated', '검증 완료'), ('active', '추천 사용'), ('review_required', '검토 필요'), ('invalid', '유효하지 않음'), ('inactive', '비활성')], db_index=True, default='validated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_tiers', to='finance.cardproduct')),
            ],
            options={
                'ordering': ['card_id', 'scope', 'minimum_spending'],
                'constraints': [models.UniqueConstraint(fields=('card', 'scope', 'minimum_spending'), name='unique_card_benefit_tier_minimum'), models.CheckConstraint(condition=models.Q(('maximum_spending__isnull', True), ('maximum_spending__gt', models.F('minimum_spending')), _connector='OR'), name='benefit_tier_max_greater_than_min')],
            },
        ),
    ]
