# Generated by Django 5.2.4 on 2026-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_benefitrule_daily_benefit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitrule',
            name='end_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefitrule',
            name='start_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
