# Generated by Django 5.2.4 on 2026-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedreport',
            name='parse_status',
            field=models.CharField(choices=[('raw', '원본'), ('normalized', '정규화'), ('validated', '검증 완료'), ('active', '추천 사용'), ('review_required', '검토 필요'), ('invalid', '유효하지 않음'), ('inactive', '비활성')], default='raw', max_length=20),
        ),
    ]
