
# Generated by Django 5.2.4 on 2026-06-23 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_category'),
        ('users', '0002_alter_useruploadedreport_parse_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('viewed', 'viewed'), ('clicked', 'clicked'), ('liked', 'liked'), ('dismissed', 'dismissed'), ('applied_for', 'applied_for')], max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_demo', models.BooleanField(default=False)),
                ('graph_sync_status', models.CharField(choices=[('pending', 'pending'), ('synced', 'synced'), ('failed', 'failed'), ('skipped', 'skipped')], default='pending', max_length=20)),
                ('graph_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='finance.cardproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', '-created_at'], name='users_userc_user_id_f87df5_idx'), models.Index(fields=['card', 'event_type', '-created_at'], name='users_userc_card_id_b496bc_idx'), models.Index(fields=['area_id', 'event_type', '-created_at'], name='users_userc_area_id_4317f9_idx')],
            },
        ),
    ]
