# Generated by Django 5.2.4 on 2026-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cardproduct_annual_fee_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitrule',
            name='maximum_transaction_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
