# Generated by Django 5.2.4 on 2026-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_benefitrule_maximum_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitrule',
            name='daily_benefit_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
